@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikhvcml6b24yIiwiaWF0IjoxNjQ3MjU0MTg3LCJleHAiOjE2NDcyNTc3ODd9.IdbxWBGipoU6mxrA1QGagM4Xg8w4MYNlcuFdl2CT6XU

GET http://localhost:3000/boards
content-type: application/json
Authorization: Bearer {{token}}


###

POST  http://localhost:3000/boards
content-type: application/json
Authorization: Bearer {{token}}

 {
     "title": "horizon2",
     "description": "wow!"
 }

###

GET http://localhost:3000/boards/2
content-type: application/json

###

DELETE http://localhost:3000/boards/1
content-type: application/json
Authorization: Bearer {{token}}

###

PATCH http://localhost:3000/boards/2/status
Content-Type: application/json

{
    "status": "PRIVATE"
}