GET http://localhost:3000/boards
content-type: application/json

###

POST  http://localhost:3000/boards
content-type: application/json

 {
     "title": "My first post",
     "description": "wow!"
 }

###

GET http://localhost:3000/boards/21336a50-9158-11ec-93ce-e10e595ee7aa
content-type: application/json

###

DELETE http://localhost:3000/boards/ba2e7880-9158-11ec-acf1-71732a65380d
content-type: application/json

###

PATCH http://localhost:3000/boards/9b5a37b0-9251-11ec-9d1b-35edd658c83a/status
Content-Type: application/json

{
    "status": "RANDOM"
}