GET http://localhost:3000/boards
content-type: application/json

###

POST  http://localhost:3000/boards
content-type: application/json

 {
     "title": "Hello",
     "description": "My first post!!"
 }